export const POSTUSERDATA_REQUEST="POSTUSERDATA_REQUEST"
export const POSTUSERDATA_SUCCESS="POSTUSERDATA_SUCCESS"
export const POSTUSERDATA_FAIL="POSTUSERDATA_FAIL"

export const GETUSERDATA_REQUEST="GETUSERDATA_REQUEST"
export const GETUSERDATA_SUCCESS="GETUSERDATA_SUCCESS"
export const GETUSERDATA_FAIL="GETUSERDATA_FAIL"